### ISSUE TITLE
Passthrough does not work with responsive css

### ISSUE THREAD

**Issue by KB1RD** [timhagn/gatsby-background-image#71] opened 2019-09-03 01:34 UTC
## Description

Hi, I encountered an issue the other day on iOS with fixed position images, so I decided to completely disable them on mobile for both performance and compatibility. To do this, I created a responsive CSS selector to set the background attachment to scroll by default and fixed on higher-res screens. This led to me encountering an issue where this plugin would not pass CSS `@media` queries on to the `::before` and `::after` selectors.

### Steps to reproduce
Create CSS like this:
```css
.bg-mobile-fixed-auto {
  background-attachment: scroll;
}
@screen md {
  .bg-mobile-fixed-auto {
    background-attachment: fixed;
  }
}
```
(`@screen` is the Tailwind CSS equivalent of `@media` and directly compiles into `@media`)

And HTML/JSX like this:
```html
    <BackgroundImage
      className="... bg-mobile-fixed-auto"
      fluid={...}
    />
```

### Expected result
`@media` queries should be transferred to CSS pseudoelements to allow responsive website design. In the case above, this would mean that the `BackgroundImage` would be scrolling on mobile and fixed on larger screens.

### Actual result
`@media` rules were not transferred to the CSS pseudoelements, so the image was not responsive. It was fixed on all screens. This is because the stylesheet that was generated was missing the `@media` rules. Here is what was on my webpage:
```css
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:before,
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:after {
            content: '';
            display: block;
            position: absolute;
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
            
            transition: opacity 0.5s ease 500ms;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
            background-attachment: scroll;
            background-position-x: center;
            background-position-y: center;
          }
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:before {
            z-index: -100;
            background-image: url('http://localhost:8000/...');
            
            opacity: 1; 
          }
          .w-full.h-half.relative.bg-mobile-fixed-auto.bg-cover.bg-center:after {
            z-index: -101;
            
            background-image: url(data:image/jpeg;base64,...);
          }
```

I had a look at the [utils code](https://github.com/timhagn/gatsby-background-image/blob/master/packages/gatsby-background-image/src/BackgroundUtils.js) and, unfortunately, this does not appear to be a trivial fix. The style detector would have to be modified to detect `@media` queries. A possible workaround is to assign the `background-attachment` values to the `::before` and `::after` selectors, so this does not need to be *super* high on the priority list. Here's the workaround that I applied:
```css
.bg-mobile-fixed-auto,
.bg-mobile-fixed-auto::before,
.bg-mobile-fixed-auto::after {
  background-attachment: scroll;
}
@screen md {
  .bg-mobile-fixed-auto,
  .bg-mobile-fixed-auto::before,
  .bg-mobile-fixed-auto::after {
    background-attachment: fixed;
  }
}
```
Finally, I should note that this does *not* apply to any responsive code, just CSS that applies to the background. As seen in the Tailwind CSS issue that was opened, things like responsive width work fine.

### Environment

```
  System:
    OS: Linux
    CPU: Intel
    Shell: /bin/bash
  Binaries:
    Node: 10.11.0 - /usr/local/bin/node
    npm: 6.11.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
  npmPackages:
    gatsby: 2.13.41 => 2.13.41
    gatsby-background-image-es5: ^0.8.2 => 0.8.2
    gatsby-image: ^2.2.7 => 2.2.7
    gatsby-plugin-postcss: 2.1.2 => 2.1.2
    gatsby-plugin-purgecss: 4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: 3.1.2 => 3.1.2
    gatsby-plugin-sharp: ^2.2.9 => 2.2.9
    gatsby-source-directus7: ^0.8.1 => 0.8.1
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4
  npmGlobalPackages:
    gatsby-cli: 2.7.0
```
Also, thanks for all the hard work that you have put into this project. It looks like you're really busy rn so sorry to bother! :) I also typed this kind of quickly and while tired, so if I missed anything, feel free to let me know.

**Comment by timhagn** [comment] 2019-09-04 06:23
Hi @KB1RD!

Thanks for the in depth view on your issue - nothing amiss or missing there, although you were tired ^^. 
And nope, at the moment `gbi` doesn't parse through media-queries, be it Tailwind's or defined otherwise. That's caused by the browsers handling of them in the `StyleSheets` pseudo-object. So you're completely right, this would sadly be no trivial thing to fix. 
Gonna have a look at it, though, as soon as I find the time and at the very least am gonna add your workaround to the Docs for the moment.
Unless, of course, you'd be so kind to open a PR adding a parapgraph about it to the Styling section ; ).

Best,

Tim.

**Comment by KB1RD** [comment] 2019-09-04 11:39
So... if I want to submit a PR, should I make the change to both the non-es5 version README and the es5 version README? (I just want to double check...)

**Comment by timhagn** [comment] 2019-09-04 13:14
Hi @KB1RD, that's of course up to you, I could change the other (non-edited) README myself, but for consistency reasons, I'd rather you would do it in both of them ; ). 
My thankfulness you'd have in either case (and I finally have to integrate All-Contributors or suchlike... % )!

**Comment by KB1RD** [comment] 2019-09-04 13:58
I'm using this in websites that I design commercially, so I think I owe you more than anything :P It's not difficult for me to mirror the changes, I just wanted to make sure that the READMEs weren't generated by software or anything

**Comment by timhagn** [comment] 2019-09-04 15:04
Wow, thanks a lot : )! Just merged it, thanks for giving back! And nope, atm. I'm still doing the READMEs the old fashioned way, but now that you point at it, maybe I should create me a small mirroring script % ).

Of course the honors of closing this issue go to you (should you be pleased with your changes ; ).

Best,

Tim.

**Closed** 2019-09-15 05:15 UTC

**Comment by as703** [comment] 2020-02-07 23:39
Many thanks for this. However, I have noticed something curious. The workaround using the ::before and ::after pseudoelements doesn't appear to work with the "background-position" style. When I try to change this to "right" or "left" for example with a media query it just stays at the default "center". However, background-attachment "fixed" or "scroll" works fine. 

Any ideas why the workaround doesn't appear to work with backgroun-position?

**Comment by joeleduardo** [comment] 2020-03-18 12:34
Same to me:
```
.class,
.class::before,
.class::after {
  background-attachment: scroll;
}
@screen md {
  .class,
  .class::before,
  .class::after {
    background-attachment: fixed;
  }
}
```
Doesn't works for background-position

**Comment by timhagn** [comment] 2020-03-23 17:32
Hi @as703 & @joeleduardo,

sry for responding so late, but you might guess the last two weeks were quite taxing.
This one might indirectly be linked with #107, gonna try digging into both this week.

Best,

Tim.

**Comment by Lisenish** [comment] 2020-12-03 10:07
@timhagn Same for me, manually set up background-position for pseudo-elements doesn't work as it described for responsive styles. The reason is that pseudo-elements got default desktop styles inferred and inserted inside a style tag in the BackgroundImage component.

Currently, I worked around that by adding `!important`to my manual styles but it's a dirty solution.
