### ISSUE TITLE
Add ability to pass custom props to the `tag` prop

### ISSUE THREAD

**Issue by dspacejs** [timhagn/gatsby-background-image#52] opened 2019-07-21 09:47 UTC
## Summary

Add the ability to pass custom props to `BackgroundImage` that are applied to the rendered `BackgroundImage.tag` prop.

### Basic example

I've created a component named `Section`. It has props such as `small` and `large` to customise its styles.

I've made another component named `BackgroundSection with the following code:

```jsx
const BackgroundSection = ({ children, ...otherProps }) => (
  <StaticQuery
    query={graphql`
      query {
        file(relativePath: { eq: "background-image.png" }) {
          childImageSharp {
            fluid(quality: 90, maxWidth: 4160) {
              ...GatsbyImageSharpFluid_withWebp
            }
          }
        }
      }
    `}
    render={(data) => {
      const imageData = data.file.childImageSharp.fluid;

      return (
        <BackgroundImage
          tag={Section}
          fluid={imageData}
          backgroundColor="#040e18"
          {...otherProps}
        >
          {children}
        </BackgroundImage>
      );
    }}
  />
);
```

This isn't passing any extra props I pass to `BackgroundSection`, such as `small` or `large`. Can this functionality please be added?

### Motivation

To enable easy customisation of the `tag` prop passed to `BackgroundImage`. Otherwise another pattern is required (e.g creating `SmallBackgroundSection` that uses a new component `SmallSection` as its `tag` prop).

**Comment by timhagn** [comment] 2019-07-21 16:19
Hi @dspacejs,

the `tag` prop directly translates to HTML Elements and defaults to a `div` container. The usage of `section` in the examples should only demonstrate that semantic tags are possible as well.
It works the same as in `gatsby-image`.
I guess you want to have differently styled `<BackgroundSection />`s with `small` or `large` classes?
This should be done by using the `className` prop.
Or did I understand your intention in a wrong way?

Best,

Tim.

**Comment by dspacejs** [comment] 2019-07-21 22:59
@timhagn here's my `Section` component:

```jsx
const Section = ({
  children, className, gray, large, small, ...otherProps
}) => {
  const fullClassName = classNames(className, {
    'bg-gray-200': gray,
    'py-16': small,
    'py-32': large,
  });

  return (
    <section className={fullClassName} {...otherProps}>
      {children}
    </section>
  );
};
```
I'm using the `small` and `large` props because it's an easy way to enforce standards. I could just create CSS classes to do this and apply it to `BackgroundSection`, this is just what I prefer to do, so it'd be nice if it could be added.

I also imagine there may be other scenarios where a developer might want to add different props to the rendered `tag`, so it'd be useful to be able to do that.

Thanks for the help.

**Comment by timhagn** [comment] 2019-07-22 07:09
Good morning @dspacejs (I'm at UTC+2 in Vienna ; ),

now I get you ^^. It's kinda related to issue #48, methinks, though while I understand wanting to use `gbi` with Gatsby's `<Link />` component to a certain degree, I guess you want to put the proverbial cart before the horse ; ).

In your case I'd rather use `<BackgroundImage />` in your `Section` component like thus:

```jsx
const Section = ({
  children, className, gray, large, small, ...otherProps
}) => {
  const fullClassName = classNames(className, {
    'bg-gray-200': gray,
    'py-16': small,
    'py-32': large,
  });

  return (
    <BackgroundImage
        Tag="section"
        className={fullClassName} 
        {...otherProps}>
      {children}
    </BackgroundImage>
  );
};
```

and then use `<Section />` instead of `<BackgroundImage />` in your `<BackgroundSection />`, as `fluid` and `backgroundColor` would then be spread into `otherProps`.

The reason I refrained from allowing other React components up till now (didn't even think about it till now, to be honest, and I would have to dig deep into the docs if this even were feasible / doable) is that it might open a can of worms and I already see `gbi`'s issue queue flowing over with issues for third party components ^^.

Should you know of a "simple" way to support custom / third party components, I'd be willing to give it a try, though : ).

Happy to help, best,

Tim.

**Comment by ArcadeRenegade** [comment] 2019-07-25 07:43
Hi @timhagn, I'll post in this thread since it's kinda of related.

I set the "id" property to my BackgroundImage components but the id is not showing up in the HTML DOM. Any idea why?

Great plugin btw.

**Comment by ArcadeRenegade** [comment] 2019-07-25 07:46
Never mind. I capitalized "Id" property and now it's working.

```
            <BackgroundImage
                Id='faq'
                Tag='section'
                className={styles.faq}
                fluid={data.faq.childImageSharp.fluid}
            >
```

**Comment by timhagn** [comment] 2019-07-25 16:03
Hi @ArcadeRenegade  / Ryan,

pew, I thought something went utterly wrong with the last Publish, see #53 ^^.
But issues as yours are one of my favorites - typos are easy to solve ; ).
Glad you figured it out, though of course I'm here to help for anything else.

Thanks for the flowers, btw.,
best,

Tim.

**Comment by ArcadeRenegade** [comment] 2019-07-26 00:46
Hi @timhagn 

Looks like when I use "Id" or "ID" then react throws me a warning. But still using "id" the attribute does not show up in the HTML dom. Any suggestions?

```
index.js:2177 Warning: Invalid DOM property `Id`. Did you mean `id`?
    in section (created by BackgroundImage)
    in BackgroundImage (at pages/index.js:135)
```

**Comment by timhagn** [comment] 2019-07-26 07:07
Hi @ArcadeRenegade,

oh, you're completely right - before the change to `noscript` bgImages, id was spliced into the elements, but I seem to have forgotten to take it out of the "redaction process" (`stripRemainingProps()` - a function to clean the remaining props used by React from the input list % ). Gonna rectify and publish it once I've really "awoken" (It's only 9AM here - that's no time for a night owl like me ; ).

Thanks for noticing and giving me a heads up to it : )!

Best,

Tim.

**Comment by timhagn** [comment] 2019-07-26 12:17
Hi @ArcadeRenegade,

just published `v0.8.1` which removes now superfluous props like id, which get spread into `<BackgroundImage />` anyway. So `id` and any "classic / basic" HTML properties should work again. Would you mind testing it : )?

And @dspacejs, shouldn't you deign to answer during the weekend although I gave you an example how you could work around your initial problem, I'm going to close this issue, as using React Components as `Tag` definitely goes beyond the scope of this package. Definitely no offense meant, but I'm starting some new projects next week and have to "get rid of" non essential issues. Hope you understand.

Best to you both,

Tim.

**Comment by ArcadeRenegade** [comment] 2019-07-26 19:05
Thank you for the quick turnaround, @timhagn !

**Comment by ArcadeRenegade** [comment] 2019-07-26 19:11
Works as intended, thanks again!

**Comment by timhagn** [comment] 2019-07-29 19:46
As written before, just have to close this for now without further information.

Though all the best,

Tim.

P.S.: Glad the small changes worked for you @ArcadeRenegade : ).

**Closed by timhagn** 2019-07-29 19:46 UTC
Labels: question
