### ISSUE TITLE
Compatiblity with Gatsby 3

### ISSUE THREAD

**Issue by tiggeymone** [timhagn/gatsby-background-image#145] opened 2021-03-03 10:20 UTC
Hello and thank you for this wonderful plugin.

Is it compatible with the new Gatsby version (v3) and the new implementation of gatsby-image? Thank you in advance!

**Comment by timhagn** [comment] 2021-03-03 12:23
Hi @tiggeymone,

it should be compatible with G3 as is - only the new `gatsby-plugin-image` will have to be accounted for like mentioned in #141.

Best,

Tim.

**Comment by i-bsd** [comment] 2021-03-03 12:31
Seems to be incompatible. Having this issue after upgrading to Gatsby v3 (which looks like it's caused by gatsby-background-image):

![mg](https://user-images.githubusercontent.com/34989694/109806177-1d9de300-7c70-11eb-9b25-4f5f6f70d428.jpg)

I have no idea what's going on here. Any suggestions?

**Comment by timhagn** [comment] 2021-03-13 10:47
Hi @tiggeymone & @i-bsd,

Closing this in favor of the mentioned #141 as an umbrella Issue.
Feel free to shout if I did err there : )!

Best,

Tim.

**Closed** 2021-03-13 10:47 UTC
