### ISSUE TITLE
Image loading issues in Safari on Mac

### ISSUE THREAD

**Issue by petrpacas** [timhagn/gatsby-background-image#9] opened 2019-03-04 12:52 UTC
Hey there - I noticed you mentioning that you [haven't checked the plugin in Safari on Mac](https://github.com/timhagn/gatsby-background-image/issues/8#issuecomment-468316342) - well, there is indeed a problem.

From what I gathered it's related to [this issue](https://github.com/gatsbyjs/gatsby/issues/4021) of the `gatsby-image` plugin.

On localhost the bg-images always load straight up w/o the "blur-up".

On live the bg-images get stuck in "blurred" phase on page load and on page change (navigation to another page on the site) the full bg-images again load (w/o the "blur-up"). If you refresh the page, you again get a stuck "blurred" bg-image.

**Comment by petrpacas** [comment] 2019-03-04 13:18
Alright, adding the IntersectionObserver polyfill as per https://github.com/gatsbyjs/gatsby/issues/4021#issuecomment-445238511 fixes this problem.

For the time being I recommend you add a note about this in the README.

**Comment by gregleeper** [comment] 2019-03-04 19:43
I was looking for a way to fix this bug this morning. Thanks for posting about it @petrpacas.

**Comment by timhagn** [comment] 2019-03-06 13:22
Finally I came around looking at this, thanks @petrpacas for finding it!
Added a small note to the current [README.md@master](https://github.com/timhagn/gatsby-background-image/blob/master/README.md) in the Install section (**Important:**)
for the moment as you suggested.
I'd be happy to receive any comments on the wording before I publish the package.
And would you mind sharing how you wrapped `BackgroundImage` - like mentioned in the [comment](https://github.com/gatsbyjs/gatsby/issues/4021#issuecomment-445238511 ) - as I'd like to add a already proven to work example?

**Comment by petrpacas** [comment] 2019-03-06 13:50
Cheers 👍 

Perhaps you could word it as follows:

> For Safari as well as Internet Explorer you have to install the IntersectionObserver and Object-fit/Object-position polyfills. At the moment of writing neither fully implements the first feature, and IE doesn't implement the latter.

As for the wrapper, I only implemented the IntersectionObserver p/f - can't help here atm...

**Comment by timhagn** [comment] 2019-03-06 14:22
Thanks for the review, am going with a combination of your latter and the first suggestion : ).
Am closing the issue for the moment as the adaptation is now published as `v0.2.41`.
But I will add some examples, as soon as a VM is set up ; ). 
And of course am gonna revisit it and  when the issue is solved over at `gatsby-image`!

**Closed by timhagn** 2019-03-06 14:22 UTC
