### ISSUE TITLE
Hiding Background Image at breakpoint

### ISSUE THREAD

**Issue by keraajohnson** [timhagn/gatsby-background-image#61] opened 2019-08-15 14:30 UTC
## Summary

I'm looking to switch out the background image at a certain breakpoint (with either nothing or just a plain colour). The class doesn't listen for whatever reason. Anyone know how to do this?

**Comment by itwasmattgregg** [comment] 2019-08-15 15:29
Do you have a url for a repo of the code you're trying?

I see gatsby-image has support for this but I'm not sure if it's built in to this package. https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-image#art-directing-multiple-images

**Comment by keraajohnson** [comment] 2019-08-15 15:31
Hey @itwasmattgregg, here's the URL. The repo is private unfortunately. 
https://optimistic-curie-af3745.netlify.com/

**Comment by timhagn** [comment] 2019-08-16 10:14
Hi @keraajohnson - and thanks @itwasmattgregg for jumping in : )!

Might it be, that this is a duplicate issue to #58? Marking is as such for the moment. Please protest if I'm wrong : )! Should I be correct, please move your conversation over there.
Gonna try working on some of `gbi`'s issue-backlog later today, and perhaps I'm gonna get around to this, as media-query / art-direction support is now asked for twice and #49 also seems to need support for media-queries % ).

Best,

Tim.

**Comment by timhagn** [comment] 2019-08-30 04:18
Hi @keraajohnson,

as this still really seems to be a duplicate of #58, I'm closing this for now, am gonna try to work on the it this weekend, but no promises % ).

Best,

Tim.

**Closed by timhagn** 2019-08-30 04:18 UTC
Labels: duplicate

**Comment by timhagn** [comment] 2019-12-02 06:33
Hi @keraajohnson & @itwasmattgregg,

shouldn't you already have noticed, art-direction support / switching images at certain breakpoints is now integrated into `gbi(es5)` since `v0.9.6`. And with a few improvements and fixes we're now at `v0.9.10`, so give it a spin, if you want. Btw. `gbitest` has been updated to show a few more of the possibilities `gbi` now has to offer : ). Just wanted to let you know.

Best,

Tim.
