### ISSUE TITLE
Image Positioning

### ISSUE THREAD

**Issue by drobinhood** [timhagn/gatsby-background-image#1] opened 2018-12-20 19:43 UTC
First, love this package, super simple.

Secondly, ideally you want the background image to truly be in the background. Currently the `<Img> `used to add the background image sits in front of {children}. Can I suggest removing the `<img>` tag once the background image is set or setting the `<img>` to display: none.

Would be happy to add a pull request in the near future if this was desired.

Thanks,

**Comment by timhagn** [comment] 2018-12-20 23:53
Hi @drobinhood, 
thanks for the compliment and the input!

Wanted to get around to it but didn't find the time till publishing.
Of course, you're completely right, the sole `<img>` must go. 
Already tried to just setting it to `display: none;`, but a white
flickering occurred. So I put it out in the wild this way, wanting
to come back to it once I refactor it with `Image()` creation
and loading instead of `gatsby-image`'s temporary images.

Contributions are always welcome, so feel free to "hack" and do a PR : ).

Thanks,

Tim.

**Comment by ambethia** [comment] 2018-12-23 06:53
Thanks for bringing this up, would love to center images. Subbing here to watch the progress, or I'll try to help out if I have time to dig into it.

**Comment by timhagn** [comment] 2019-01-07 16:19
Will try to look into it this week, was on a "hiatus" over the holidays and the last week ; ).
Thanks again to @ambethia for PR #2!

**Comment by timhagn** [comment] 2019-01-11 14:41
With my changes after PR #2 this issue might be solved, for the moment...
At least the placeholder-image now has `display: none;`.
If it isn't for anyone of you, then please tell me, which `img` you meant exactly.
Would you mind to check it? New npmjs version is 0.1.11.

**Comment by timhagn** [comment] 2019-01-11 19:05
Next PR, next Version: after PR #3 for the README, version now's ticked at 0.1.12 on npmjs.

**Comment by timhagn** [comment] 2019-01-18 14:07
@drobinhood & @ambethia Just working on `v0.2.0`, removing all the superfluous remaining placeholder-tags and switching to load handling with `Image()`.
There your issue should be completely gone (as there are no tags except on <noscript> left ; ).
But would you please check, if this is already solved as mentioned in my (comment above)[https://github.com/timhagn/gatsby-background-image/issues/1#issuecomment-453538173], so I can close this Issue anyhow?

**Comment by timhagn** [comment] 2019-01-18 17:33
@drobinhood @ambethia `0.2.0` has just been published, please test : ).

**Comment by ambethia** [comment] 2019-01-18 19:13
Will do! I've been so busy, so I haven't had time to respond and test the
previous changes.

>

**Comment by vititu** [comment] 2019-01-19 15:43
Is it possible to add a `background-position`?

I'm trying to target the `:after` pseudo-element but it seems like it strips the properties out of it.

**Comment by timhagn** [comment] 2019-01-20 06:34
Hi @vititu,

silly to ask, but have you given an own `classId` to your Element and targeting it's `:after`?
So, after the obligatory "debasement" is done ( ; ), would you have some exemplary code
I might reproduce? ATM nothing should be stripped away, which isn't in a media-query.
But I'm ready to dive in : )!

Greetz,

Tim.

**Comment by timhagn** [comment] 2019-01-22 12:09
Hi @vititu, 

I've now included examples on how to target the pseudo-elements in the [gbitest repo](https://github.com/timhagn/gbitest).

Greetz, 

Tim.

**Comment by drobinhood** [comment] 2019-01-30 12:15
@timhagn been quite busy myself. It appears to be working fine for me in terms of my original issue. Thank you. Also thanks for adding those examples.

**Comment by timhagn** [comment] 2019-01-30 15:58
@drobinhood Thanks for testing - methinks this should work as intended, now, so I'm closing the issue FTM.

**Closed by timhagn** 2019-01-30 15:58 UTC
