### ISSUE TITLE
Media queries?

### ISSUE THREAD

**Issue by erichodges** [timhagn/gatsby-background-image#80] opened 2019-09-24 21:29 UTC
Is there a way to use media queries to select the image to load?

**Comment by timhagn** [comment] 2019-09-25 07:06
Hi @erichodges,

this seems to be a duplicate of #58 and the already closed (duplicate) #61. 
Please have a look at both of them, as this is definitely in the making, but my time is quite sparse, sadly, at the moment : /.
Let's continue this in #58 (just write a comment or give a thumbs up / +1 ; ), OK?
Am closing this now, but feel free to give me a shout, should you talk about anything different : ).

Best,

Tim.

**Closed by timhagn** 2019-09-25 07:06 UTC
Labels: duplicate
